ewarehouse-apex/api/src/objects/Commodities__c.object
<CustomObject>
    <fields>
        <fullName>Effective_date__c</fullName>
        <description>The date from which the entered prices are effective. A price for the same commodity with a later date will supersede any previous prices.</description>
        <inlineHelpText>Enter the date from which these prices will be effective for this commodity. A price for the same commodity with a later date will supersede any previous prices.</inlineHelpText>
        <label>Effective date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Highest_Wholesale_Price__c</fullName>
        <label>Highest Wholesale Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Markets__c</referenceTo>
        <relationshipLabel>Commodities</relationshipLabel>
        <relationshipName>Commodities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commodities</label>
    <nameField>
        <label>Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commodities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Land_Size__c</fullName>
        <description>Amount of land, in acres, owned by the farmer</description>
        <label>Land Size (Acres)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Accepted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Accepted</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Harvested__c</fullName>
        <label>Quantity Harvested</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Rejected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Rejected</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Harvest</label>
    <nameField>
        <displayFormat>H{000000}</displayFormat>
        <label>Harvest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Loan__c.object
<CustomObject>
    <description>The loan that has been taken out by the farmer</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Harvest</label>
        <referenceTo>Harvest__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Day + Month + Year that the person was born</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raw_Mobile_Number__c</fullName>
        <description>(optional) Phone number provided for non GF-assets</description>
        <label>Raw Mobile Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Sale__c.object
<CustomObject>
    <description>Represents a sale transaction from the warehouse</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <description>The farmer who is selling their produce</description>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Sales</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The harvest from which this sale is being made</description>
        <label>Harvest</label>
        <referenceTo>Harvest__c</referenceTo>
        <relationshipLabel>Sales</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the transaction was made</description>
        <label>Sale Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Sale_Farmer_Association__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Applied__c</fullName>
        <formula>( Beans_Number_of_90kg_Bags_Sold__c *  Sale__r.Beans_Price_Per_90kg_Bag__c ) +
( Cow_Peas_Number_of_90kg_Bags_Sold__c *  Sale__r.Cow_Peas_Price_Per_90kg_Bag__c ) +
( Dolichos_Number_of_90kg_Bags_Sold__c *  Sale__r.Dolichos_Price_Per_90kg_Bag__c ) +
( Green_Grams_Number_of_90kg_Bags_Sold__c *  Sale__r.Dolichos_Price_Per_90kg_Bag__c ) +
( Maize_Number_of_90kg_Bags_Sold__c *  Sale__r.Maize_Price_Per_90kg_Bag__c ) +
( Pigeon_Peas_Number_of_90kg_Bags_Sold__c *  Sale__r.Pigeon_Peas_Price_Per_90kg_Bag__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Applied</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Sale Farmer Associations</relationshipLabel>
        <relationshipName>Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fee_Due__c</fullName>
        <label>Fee Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <label>Sale</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Sale Farmer Associations</relationshipLabel>
        <relationshipName>Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sale Farmer Associaton</label>
    <nameField>
        <displayFormat>SF-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Farmers Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/PaymentAllocationReportControllerTest.cls
@isTest
public with sharing class PaymentAllocationReportControllerTest {
	
    static testMethod void testLeadData(){
    	insertTestData();
    	PaymentAllocationReportController controller = new PaymentAllocationReportController();
        controller.startDate = Date.newinstance(2013, 8, 16);
        //controller.endDate = Date.newinstance(2013, 8, 16);
        
        List<PaymentAllocationReportController.PaymentAllocation> payments = controller.getPayments();
        
        System.assertEquals(0, payments.size());
	}
   
	
	

    private static void insertTestData(){
    	// create and insert country
        Country__c country = getTestCountry();
        insert country;
        
        // create and insert district
        District__c district = getTestDistrict();
        insert district;
        
        // create and insert 2 Persons
        Person__c person1 = getTestPerson(country, district);
        Person__c person2 = getTestPerson(country, district);
        person2.First_Name__c = 'John';
        person2.Last_Name__c = 'Lennon';
        person2.Gender__c = 'Male';
        insert person1;
        insert person2;
        
        // with the person id, create and insert a Farmer
        Farmer__c farmer1 = getTestFarmer(person1);
        Farmer__c farmer2 = getTestFarmer(person2);
        farmer2.Name = '2eyUUD';
        farmer2.Land_Size__c = 10;
        insert farmer1;
        insert farmer2;
        
        Group__c group1 = getGroup();
        insert group1;
        
        Person_Group_Association__c pga1 = getPersonGroupAsso(group1, person1);
        Person_Group_Association__c pga2 = getPersonGroupAsso(group1, person2);
        insert pga1;
        insert pga2;
        
        Harvest__c harvest1 = getHarvest(farmer1);
        Harvest__c harvest2 = getHarvest(farmer2);
        Harvest__c harvest3 = getHarvest(farmer2);
        harvest1.Quantity_Accepted__c = 10;
        harvest1.Quantity_Harvested__c = 11;
        harvest1.Quantity_Rejected__c = 1;
        harvest2.Quantity_Accepted__c = 10;
        harvest2.Quantity_Harvested__c = 11;
        harvest2.Quantity_Rejected__c = 1;
        harvest3.Quantity_Accepted__c = 5;
        harvest3.Quantity_Harvested__c = 7;
        harvest3.Quantity_Rejected__c = 2;
        harvest3.Crop__c = 'Maize';
        insert harvest1;
        insert harvest2;
        insert harvest3;
        
        // create a loan
        Loan__c loan1 = getLoan(farmer1, harvest1);
        Loan__c loan2 = getLoan(farmer2, harvest2);
        insert loan1;
        insert loan2;
        
        Markets__c market1 = getMarket();
        insert market1;
        
        Commodities__c commodity1 = getCommodity(market1);
        Commodities__c commodity2 = getCommodity(market1);
        Commodities__c commodityExisting = getCommodity(market1);
        commodity2.Name = 'Maize';
        commodityExisting.Market__c = null;
        commodityExisting.Effective_date__c = null;
        commodityExisting.Highest_Wholesale_Price__c = null;
        insert commodityExisting;
        insert commodity1;
        insert commodity2;
        
        Sale__c sale1 = getSale();
        Sale__c sale2 = getSale();
        sale2.Status__c = 'New';
        sale2.Beans_Number_of_90kg_Bags_Sold__c = 1;
        sale2.Beans_Price_Per_90kg_Bag__c = 1000;
        sale2.Sale_Date__c = Date.newInstance(2013, 8, 16);
        insert sale1;
        insert sale2;
        
        Sale_Farmer_Association__c sf1 = getSaleFarmer(sale1, farmer1);
        Sale_Farmer_Association__c sf2 = getSaleFarmer(sale1, farmer2);
        Sale_Farmer_Association__c sf3 = getSaleFarmer(sale2, farmer1);
        sf1.Beans_Number_of_90kg_Bags_Sold__c = 2;
        sf2.Beans_Number_of_90kg_Bags_Sold__c = 0;
        sf3.Beans_Number_of_90kg_Bags_Sold__c = 1;
        sf1.Cow_Peas_Number_of_90kg_Bags_Sold__c = 2;
        sf2.Cow_Peas_Number_of_90kg_Bags_Sold__c = 1;
        sf3.Cow_Peas_Number_of_90kg_Bags_Sold__c = 0;
        //sf1.Fee_Due__c = sf1.Amount_Applied__c * 0.01;
        //sf2.Fee_Due__c = sf2.Amount_Applied__c * 0.01;
        //sf3.Fee_Due__c = sf3.Amount_Applied__c * 0.01;
        insert sf1;
        insert sf2;
        insert sf3;
        
        
    }

    // mock data for test runs
    public static District__c getTestDistrict(){
        District__c district = new District__c();
        district.Name = 'Isiolo';
        return district;
    }
    
    public static Country__c getTestCountry(){
        Country__c country = new Country__c();
        country.Name = 'Kenya';
        country.ISO_Standard_Code__c = 'KE';
        country.Language__c = 'Swahili';
        return country;
    }

    public static Person__c getTestPerson(Country__c country, District__c district){
        
        Person__c person = new Person__c();
        
        person.First_Name__c = 'Jane';
        person.Middle_Name__c = 'The Actrice';
        person.Last_Name__c = 'Fonda';
        person.Date_of_Birth__c = date.newinstance(1937, 12, 21);
        person.Raw_Mobile_Number__c = '+254123456789';
        person.Gender__c = 'Female';
        person.Village__c = 'Kisumu';
        person.City__c = 'Kisumu city';
        person.District__c = district.Id;
        person.Country__c = country.Id;
        person.ID_Number__c = 'ID0987654321';
        person.Picture_URL__c = 'http://www.himmelreich-it.com/image.jpg';
        person.Next_Of_Kin__c = 'Ted Turner';
        person.Next_Of_Kin_Telephone__c = '+254123456788';
        
        return person;
    }
    
    public static Farmer__c getTestFarmer(Person__c person){
        Farmer__c farmer = new Farmer__c();
        farmer.Name = '3eyUUD';
        farmer.Person__c = person.Id;
        farmer.Status__c = 'Processed';
        farmer.Sale_Status__c = 'Paid';
        farmer.Land_Size__c = 35;
        farmer.Crops__c = 'Maize';
        farmer.Livestock__c = 'Goats';
        return farmer;
    }
    
    public static Group__c getGroup(){
        Group__c groupC = new Group__c();
        groupC.Name = 'Kiruri Farmers';
        groupC.Group_ID__c = 'A12/012/001/002';
        return groupC;
    }
    
    public static Person_Group_Association__c getPersonGroupAsso(Group__c groupC, Person__c person){
        Person_Group_Association__c pga = new Person_Group_Association__c();
        pga.Group__c = groupC.Id;
        pga.Person__c = person.Id;
        return pga;
    }
    
    public static Harvest__c getHarvest(Farmer__c farmer){
        Harvest__c h = new Harvest__c();
        h.Crop__c = 'Beans';
        h.Date_Harvested__c = date.newinstance(2013, 4, 30);
        h.Farmer__c = farmer.Id;
        h.Quantity_Accepted__c = 10;
        h.Quantity_Harvested__c = 11;
        h.Quantity_Rejected__c = 1;
        h.Storage_Location__c = 'Home';
        return h;
    }
    
    public static Loan__c getLoan(Farmer__c farmer, Harvest__c harvest){
        
        Loan__c loan = new Loan__c();
        loan.Amount_Applied_For__c = 130000;
        loan.Amount_Approved__c = 120000;
        loan.Application_Date__c = date.newinstance(2013, 4, 30);
        loan.Decision_Date__c = date.newinstance(2013, 5, 1);
        loan.Balance__c = 120000;
        loan.Status__c = 'Applied';
        loan.Currency__c = 'KES';
        loan.Farmer__c = farmer.Id; 
        if(harvest != null)
            loan.Harvest__c = harvest.Id; 
        
        return loan;
        
    }
    
    public static Sale__c getSale(){
        Sale__c sale = new Sale__c();
        sale.Status__c = 'New';
        sale.Beans_Number_of_90kg_Bags_Sold__c = 2;
        sale.Beans_Price_Per_90kg_Bag__c = 2000;
        sale.Cow_Peas_Number_of_90kg_Bags_Sold__c = 3;
        sale.Cow_Peas_Price_Per_90kg_Bag__c = 1500;
        sale.Sale_Date__c = Date.newInstance(2013, 8, 16);
        return sale;
        
    }
    
    public static Sale_Farmer_Association__c getSaleFarmer(Sale__c sale, Farmer__c farmer){
        Sale_Farmer_Association__c sf = new Sale_Farmer_Association__c();
        
        sf.Farmer__c = farmer.Id;
        sf.Sale__c = sale.Id;
        sf.Beans_Number_of_90kg_Bags_Sold__c = 2;
        sf.Cow_Peas_Number_of_90kg_Bags_Sold__c = 3;
        sf.Fee_Due__c = sf.Amount_Applied__c != null ? sf.Amount_Applied__c * 0.01 : 0;
        sf.Fee_Paid__c = 0;
        return sf;
    }
    
    public static Markets__c getMarket(){
        Markets__c m = new Markets__c();
        
        m.Name = 'e-warehouse';
        
        return m;
        
    }
    
    public static Commodities__c getCommodity(Markets__c market1){
        Commodities__c c = new Commodities__c();
        
        c.Name = 'Beans';
        c.Effective_date__c = Date.newInstance(2010, 1, 1);
        c.Market__c = market1.Id;
        c.Highest_Wholesale_Price__c = 200;
        
        return c;
        
    }
 
}