ewarehouse-apex/api/src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Accepted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Accepted</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Harvested__c</fullName>
        <label>Quantity Harvested</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Rejected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Rejected</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Harvest</label>
    <nameField>
        <displayFormat>H{000000}</displayFormat>
        <label>Harvest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Loan__c.object
<CustomObject>
    <description>The loan that has been taken out by the farmer</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Harvest</label>
        <referenceTo>Harvest__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Contract_No__c</fullName>
        <label>Loan Contract No</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/HarvestAndLoanSurveyController.cls
public with sharing class HarvestAndLoanSurveyController extends DynamicDashboardBaseController{
    public HarvestAndLoanSurveyController() {
        setDashboardName('Harvest & Loan Dashboard');
        setSections(loadSections());
    }
    
    public List<Harvest__c> getLeadData(){
    	List<Harvest__c> harvestList = [SELECT 
											Id,
											Name,
											Crop__c,
											Farmer__r.Name,
											Farmer__r.Person__r.First_Name__c,
											Farmer__r.Person__r.Middle_Name__c,
											Farmer__r.Person__r.Last_Name__c,
											Farmer__r.Person__r.ID_Number__C,
											Quantity_Harvested__c,
											Quantity_Accepted__c,
											Quantity_Rejected__c
											FROM Harvest__c
											WHERE Farmer__c NOT IN (SELECT Farmer__c FROM Loan__c WHERE Loan_Contract_No__c != '')
											ORDER BY Farmer__c ASC NULLS FIRST];
	   return harvestList;
    }
    
    public PageReference exportPage(){
    	PageReference newPage = new PageReference('/apex/HarvestAndLoanSurveyExport');
    	
    	return newPage;
    }
    
    public String getFileName(){
        return 'harvestloan-export-' + DateTime.now().format('yyyyMMddHHmmss');
    }
    public String getRunDate(){
        return DateTime.now().format('dd MMM yyyy, HH:mm:ss');
    }
}