ewarehouse-apex/api/src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Day + Month + Year that the person was born</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/ClientWS.cls
@RestResource(urlMapping='/client/*')
global class ClientWS extends ServiceResponses {
	
 	@HttpGet
    global static ServiceResponses.ServiceResultResponse getClient() {
    	
    	Map<String, String> params = null;
		
		// get the id from the request parameter
		String id = RestContext.request.params.get('id');
		
		if(id == null){
			System.debug('ERROR: request param [id] should not be null');
			return new ErrorResponse('400', 'We could find required parameter [id]');
		}
        
        system.debug('id = ' + id);
        																
        List<Farmer__c> lstClient = getFarmer(id);
		
		if (lstClient.size() > 0)
		{
			// TODO catch of not able to get the farmer to a client object
			Farmer__c clObj = lstClient.get(0);
			return new ClientWS.ClientResponse('200', 'OK', Client.fromFarmer(clObj));
		}
		else{
			System.debug('no Farmer found with ID:' + id);
			return new ErrorResponse('400', 'We could find a client with the gived id: ['+id+']');
		}
	}

	/*
	@HttpPatch
	global static String updateClient(){
		
		// take the client from the parameters
		String jsonString = RestContext.request.params.get('client');	
		system.debug('json: ' + jsonString);
		
		// parse the client data
		Client updateClient = (Client) JSON.deserialize(jsonString, Client.class);
		system.debug(updateClient);
		
		// get the appropriate client
		List<Farmer__c> lstClient= getFarmer(updateClient.id);
		
		// check if the client exists
		if (lstClient.size() > 0)
		{
			Farmer__c clObj = lstClient.get(0);
	        
	        clObj.Name = updateClient.name;
	        clObj.eu_himmit__Date_of_birth__c = updateClient.dateOfBirth;
	        clObj.eu_himmit__Time_authorized__c = updateClient.timeAuthorized;
	        clObj.eu_himmit__Married__c = updateClient.married;
			
			Database.SaveResult results = Database.update(clObj);
			system.debug(results);
			
			//if(results.isSuccess() == 'true')
				return 'success';
		
		}
		return 'error';
	}
	*/
	
	global class ClientResponse extends ServiceResultResponse {
		public ClientResponse(String code, String description, Client client){
			this.code = code;
			this.description = description;
			this.client = client;
		}
		
		public Client client;
	}
	
	private static List<Farmer__c> getFarmer(String name){
		return [SELECT 
					ID, 
					Name, 
					Person__r.First_Name__c,
					Person__r.Last_Name__c,
					Person__r.Date_of_Birth__c,
					Person__r.Mobile_Number__c,
					Person__r.Phone_Number__c,
					Person__r.ID_Number__c,
					Person__r.Village__c,
					Person__r.District__r.Name,
					Person__r.City__c,
					Person__r.Country__r.Name,
					Person__r.Gender__c
				FROM Farmer__c WHERE Name = :name];

	}
	
	
}