ewarehouse-apex/api/src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sale_Status__c</fullName>
        <label>Sale Status</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Day + Month + Year that the person was born</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <label>Group ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Of_Kin_Telephone__c</fullName>
        <label>Next Of Kin Telephone</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Of_Kin__c</fullName>
        <label>Next Of Kin</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/Client.cls
global with sharing class Client {
	
	public String Id { get; set; }
	public String FirstName { get; set; }
	public String MiddleName { get; set; }
    public String LastName { get; set; }
    public Date DateOfBirth { get; set; }
    public String MobileNumber { get; set; }
    public String IDNumber { get; set; }
    public String Gender { get; set; }
    public String Village { get; set; }
    public String District { get; set; }
    public String City { get; set; }
    public String Country { get; set; }
    public String PictureURL { get; set; }
    public Blob Picture { get; set; }
    
    public String NextOfKin { get; set; }
    public String NextOfKinTelephone { get; set; }
    public String CPGId { get; set; }
    public String CPGName { get; set; }
    public String SaleStatus {get; set; }
    
    
    //photo,Next of Kin Name and Next of Kin Telephone
    
    
    public static Client fromFarmer(Person__c person){
    	
    	List<Farmer__c> farmerRef = person.Farmers__r;
    	// farmer should not be null
    	if(farmerRef.size() == 0)
    		return null;
    	
    	District__c districtRef = person.District__r;
    	Country__c countryRef = person.Country__r;
    	List<Person_Group_Association__c> pgaRef = person.PersonGroupAssociations__r;
    	
    	// create new client
        Client client = new Client();
    	client.Id = farmerRef[0].Name;
    	client.SaleStatus = farmerRef[0].Sale_Status__c; 
    	
    	// take the information from the referenced objects when they are available
		client.FirstName = person.First_Name__c;
		client.MiddleName = person.Middle_Name__c;
	    client.LastName = person.Last_Name__c;
	    client.DateOfBirth = person.Date_of_Birth__c;
	    client.MobileNumber = person.Mobile_Number__c;
	    client.IDNumber = person.ID_Number__c;
	    client.Gender = person.Gender__c;
	    client.Village = person.Village__c;
	    client.City = person.City__c;
	    client.PictureURL = person.Picture_URL__c;
	    client.Picture = getImage(client.PictureURL);
	    client.NextOfKin = person.Next_Of_Kin__c;
	    client.NextOfKinTelephone = person.Next_Of_Kin_Telephone__c;
		
    	if(districtRef != null)
			client.District = districtRef.Name;
			
		if(countryRef != null)
	    	client.Country = countryRef.Name;
	    	
	    if(pgaRef.size() > 0){
	    	Group__c groupRef = pgaRef[0].Group__r;
	    	if(groupRef != null){
		    	client.CPGId = groupRef.Group_ID__c;
		    	client.CPGName = groupRef.Name;	
	    	}
	    	
	    }
	    
		system.debug(client);
		
		return client;
    }
    
    private static Blob getImage(String url){
    	if(url == null)
    		return null;
    		
		try{
			Http h = new Http();
			HttpRequest req = new HttpRequest();
			
			//Replace any spaces with %20
			url = url.replace(' ', '%20');
			req.setEndpoint(url);
			req.setMethod('GET');
			
			//If you want to get a PDF file the Content Type would be 'application/pdf'
			req.setHeader('Content-Type', 'image/jpeg');
			req.setCompressed(true);
			req.setTimeout(60000);
			                 
			HttpResponse res = null;
			res = h.send(req);
			//These next three lines can show you the actual response for dealing with error situations
			string responseValue = '';
			responseValue = res.getBody();
			
			// Get the body of the response as blob
			blob image = res.getBodyAsBlob();
	                
			return image;
    	}
    	catch(Exception e){
    		system.debug(e);
    		// return null when an exception was thrown
    		return null;
    	}
    	
    }
    
}