ewarehouse-apex/api/src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Crops__c</fullName>
        <description>Top crops grown by the farmer</description>
        <label>Crops</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wheat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Potatoes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundnuts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorghum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bananas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Land_Size__c</fullName>
        <description>Amount of land, in acres, owned by the farmer</description>
        <label>Land Size (Acres)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Livestock__c</fullName>
        <description>Livestock kept by the farmer</description>
        <label>Livestock</label>
        <picklist>
            <picklistValues>
                <fullName>Cattle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chickens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkeys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donkeys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rabbits</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sale_Status__c</fullName>
        <label>Sale Status</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Accepted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Accepted</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Harvest</label>
    <nameField>
        <displayFormat>H{000000}</displayFormat>
        <label>Harvest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Loan__c.object
<CustomObject>
    <description>The loan that has been taken out by the farmer</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Harvest</label>
        <referenceTo>Harvest__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Sale__c.object
<CustomObject>
    <description>Represents a sale transaction from the warehouse</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <description>The farmer who is selling their produce</description>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Sales</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The harvest from which this sale is being made</description>
        <label>Harvest</label>
        <referenceTo>Harvest__c</referenceTo>
        <relationshipLabel>Sales</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_Sold__c</fullName>
        <label>Volume Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/EWarehouseMEDashboardController.cls
public with sharing class EWarehouseMEDashboardController  {
	private static List<String> crops = null;
    private static List<String> livestocks = null;
    
	private String farmersTrained = 'No of Farmers registered';
	private Integer acreSteps = 5;
	
	//private Map<String, String> impactData;
	private List<NameCount> impactData;
	private List<NameCount> farmersByGender;
	private List<NameCount> farmersByAcre;
	private List<NameCount> farmersByCrop;
	private List<NameCount> farmersByLivestock;
	private List<NameCount> grainCollected;
	private List<NameCount> grainSold;
	
	private List<IntegerRange> acreRanges;
	
    public EWarehouseMEDashboardController() {
    	loadData();        
    }
    
    private void loadData(){
    	// set defaults, ranges and values
    	acreRanges = new List<IntegerRange>();
    	acreRanges.add(new IntegerRange(0, 10));
    	acreRanges.add(new IntegerRange(11, 20));
    	acreRanges.add(new IntegerRange(21, 30));
    	acreRanges.add(new IntegerRange(31, 40));
    	acreRanges.add(new IntegerRange(41, -1));
    	
    	loadCropsValues();
    	loadLivestockValues();
    	
    	// reset all the data
    	impactData = new List<NameCount>();
        farmersByGender = new List<NameCount>();
        farmersByAcre = new List<NameCount>();
    	farmersByCrop = new List<NameCount>();
    	farmersByLivestock = new List<NameCount>();
    	grainCollected = new List<NameCount>();
    	grainSold = new List<NameCount>();
    	
    	// load farmers by gender and also set the total farmers
    	loadFarmersByGender();
    	loadVKWInformation();
    	loadFarmersByAcre();
    	loadFarmersByCrop();
    	loadFarmersByLivestock();
    	loadLoanInformation();
    	loadFarmersWhoArePaid();
    	loadGrainCollected();
    	loadGrainSold();
    }
    
    public List<NameCount> getImpactData(){
        return impactData;
    }
    
    public List<NameCount> getFarmersByGender(){
        return farmersByGender;
    }
    public List<NameCount> getFarmersByAcre(){
        return farmersByAcre;
    }
    public List<NameCount> getFarmersByCrop(){
        return farmersByCrop;
    }
    public List<NameCount> getFarmersByLivestock(){
        return farmersByLivestock;
    }
    public List<NameCount> getGrainCollected(){
        return grainCollected;
    }
    public List<NameCount> getGrainSold(){
        return grainSold;
    }
    
    private void loadFarmersByGender(){
    	Integer totalFarmers = 0;
        
        for(AggregateResult ar: [SELECT Person__r.Gender__c, COUNT(Id) c FROM Farmer__c GROUP BY Person__r.Gender__c ORDER BY Person__r.Gender__c DESC]){
            farmersByGender.add(new NameCount(String.valueOf(ar.get('Gender__c')), String.valueOf(ar.get('c'))));
            totalFarmers += Integer.valueOf(ar.get('c'));
        }
        
        // add the total amount of farmers to the impactData
        impactData.add(new NameCount(farmersTrained, String.valueOf(totalFarmers)));
        for(NameCount nc : farmersByGender){
        	impactData.add(nc);
        }
    }
    
    private void loadVKWInformation(){
        Integer vkws = Database.countQuery('SELECT COUNT() FROM Person__c WHERE Type__c = \'VKW\'');
        impactData.add(new NameCount('No of Village Knowledge Workers registered', String.valueOf(vkws)));
    }
    
    private void loadFarmersWhoArePaid(){
        Integer result = Database.countQuery('SELECT COUNT() FROM Farmer__c WHERE Sale_Status__c = \'Paid\'');
        impactData.add(new NameCount('No of farmers fully paid for sales', String.valueOf(result)));
    }
    
    private void loadFarmersByAcre(){
    	// make sure they are sorted to loop through them correctly
    	acreRanges.sort();
    	
    	for (IntegerRange range : acreRanges){
    		Integer stepMin = range.min;
    		Integer stepMax = range.max;
    		String q;
    		if(stepMax != -1)
                q = 'SELECT Count() FROM Farmer__c WHERE Land_Size__c >= '+stepMin+' AND Land_Size__c <= '+stepMax;
            else
                q = 'SELECT Count() FROM Farmer__c WHERE Land_Size__c >= '+stepMin;
                
            Integer result = Database.countQuery(q);
            if(stepMax != -1)
                farmersByAcre.add(new NameCount(stepMin+' - '+stepMax, String.valueOf(result)));
            else
                farmersByAcre.add(new NameCount('> ' + (stepMin - 1), String.valueOf(result)));
        }
        
        system.debug(LoggingLevel.Debug, farmersByAcre);
    }
    
    private void loadFarmersByCrop(){
    	for(String crop : crops){
    		String q = 'SELECT COUNT() FROM Farmer__c WHERE Crops__c includes (\''+crop+'\')';
    		Integer result = Database.countQuery(q);
    		if(result > 0){
                farmersByCrop.add(new NameCount(crop, String.valueOf(result)));	
    		}
    	}
    }
    
    private void loadFarmersByLivestock(){
    	for(String livestock : livestocks){
            String q = 'SELECT COUNT() FROM Farmer__c WHERE Livestock__c includes (\''+livestock+'\')';
            Integer result = Database.countQuery(q);
            if(result > 0){
                farmersByLivestock.add(new NameCount(livestock, String.valueOf(result))); 
            }
        }
    }
    
    private void loadLoanInformation(){
    	//
    	Integer repaidLoans = 0;
        Integer totalLoans = 0;
        for(AggregateResult ar: [SELECT COUNT(ID) c, Status__c FROM Loan__c GROUP BY Status__c]){
        	Integer cnt = Integer.valueOf(ar.get('c'));
        	String status = String.valueOf(ar.get('Status__c'));
        	
        	if(status == 'Repaid'){
        		repaidLoans = cnt;
        	}
        	
        	if(status == 'Approved' || status == 'Service' || status == 'Repaid' || status == 'Overdue'){
        		totalLoans += cnt;
        	}
        }
        
        impactData.add(new NameCount('Total loans', String.valueOf(totalLoans)));
        impactData.add(new NameCount('Repaid loans', String.valueOf(repaidLoans)));
        Decimal ratio = (repaidLoans / (Decimal)totalLoans);
        impactData.add(new NameCount('Repaid ratio (loans)', String.valueOf(ratio.setScale(2))));
    }
    
    private void loadGrainCollected(){
    	for(AggregateResult ar: [SELECT SUM(Quantity_Accepted__c) s, Crop__c FROM Harvest__c GROUP BY Crop__c]){
    		Integer quantity = Integer.valueOf(ar.get('s'));
    		String crop = String.valueOf(ar.get('Crop__c'));
    		Integer tons = (quantity * 90) / 1000;
            grainCollected.add(new NameCount(crop, String.valueOf(tons)));
        }
        system.debug(grainCollected);
    }
    
    private void loadGrainSold(){
        for(AggregateResult ar: [SELECT SUM(Volume_Sold__c) vs, Harvest__r.Crop__c FROM Sale__c GROUP BY Harvest__r.Crop__c]){
        	system.debug('aggregate loop');
        	if(ar.get('vs') != null && ar.get('Crop__c') != null){
        		Integer quantity = Integer.valueOf(ar.get('vs'));
	            String crop = String.valueOf(ar.get('Crop__c'));
	            Integer tons = (quantity * 90) / 1000;
	            system.debug(tons);
	            system.debug(grainSold);
	            grainSold.add(new NameCount(crop, String.valueOf(tons)));
        	}
        }
        system.debug(grainSold);
    }

    private static void loadCropsValues() {
        if(crops == null){
            crops = new List<String>();
            for(Schema.PicklistEntry entry : Farmer__c.Crops__c.getDescribe().getPicklistValues()){
                crops.add(entry.getValue());
            }
        }
    }
    
    private static void loadLivestockValues() {
        if(livestocks == null){
            livestocks = new List<String>();
            for(Schema.PicklistEntry entry : Farmer__c.Livestock__c.getDescribe().getPicklistValues()){
                livestocks.add(entry.getValue());
            }
        }
    }
    
    public class NameCount {
        public String name { get; set; }
        public String count { get; set; }

        public NameCount(String name, String count) {
            this.name = name;
            this.count = count;
        }
    }
    
    public class IntegerRange implements Comparable {
        public Integer min { get; set; }
        public Integer max { get; set; }

        public IntegerRange(Integer min, Integer max) {
            this.min = min;
            this.max = max;
        }
        
        // Implement the compareTo() method
	    public Integer compareTo(Object compareTo) {
	        IntegerRange compareToEmp = (IntegerRange)compareTo;
	        if (min == compareToEmp.min) return 0;
	        if (min > compareToEmp.min) return 1;
	        return -1;        
	    }
    }
    
}