ewarehouse-apex/api/src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Quality_Rating__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Quality Rating</label>
        <referenceTo>Quality_Rating__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Harvested__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date Harvested</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Quality_Rating__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Quality Rating</label>
        <referenceTo>Quality_Rating__c</referenceTo>
        <relationshipLabel>Harvests (Previous Quality Rating)</relationshipLabel>
        <relationshipName>Harvests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Accepted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Accepted</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Harvested__c</fullName>
        <label>Quantity Harvested</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Rejected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Rejected</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage_Location__c</fullName>
        <label>Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Harvest</label>
    <nameField>
        <displayFormat>H{000000}</displayFormat>
        <label>Harvest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Loan__c.object
<CustomObject>
    <description>The loan that has been taken out by the farmer</description>
    <fields>
        <fullName>Amount_Applied_For__c</fullName>
        <description>The amount that the farmer has applied for</description>
        <label>Amount Applied For</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_Approved__c</fullName>
        <description>The amount that was approved for disbursement to the farmer</description>
        <label>Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Application Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Decision Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Harvest</label>
        <referenceTo>Harvest__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/Loan.cls
public with sharing class Loan {
	public String Id { get; set; }
	public String FarmerId { get; set; }
	public Decimal AmountApplied { get; set; }
	public Decimal AmountApproved { get; set; }
	public Decimal Balance { get; set; }
	public Date ApplicationDate { get; set; }
	public Date DecisionDate { get; set; }
	public String Status { get; set; }
	public Loan.Harvest Harvest {get; set; }
	
	public static Loan fromSObject(Loan__c loan){
		// get a reference of the farmer's person object
    	Farmer__c farmerRef = loan.Farmer__r;
    	Harvest__c harvestRef = loan.Harvest__r;
    	
    	Loan l = new Loan();
		l.Id = loan.Id;
		l.AmountApplied = loan.Amount_Applied_For__c;
		l.AmountApproved = loan.Amount_Approved__c;
		l.Balance = loan.Balance__c;
		l.ApplicationDate = loan.Application_Date__c;
		l.DecisionDate = loan.Decision_Date__c;
		l.Status = loan.Status__c;
		
    	// take the information from the referenced objects when they are available
    	if(farmerRef != null){
    		l.FarmerId = farmerRef.Name;	
    	}
    	
    	if(harvestRef != null){
    		//Quality_Rating__c cqrRef = harvestRef.Current_Quality_Rating__r;
    		//Quality_Rating__c pqrRef = harvestRef.Previous_Quality_Rating__r;
    		Loan.Harvest h = new Harvest();
    		h.Crop = harvestRef.Crop__c;
    		h.DateHarvested = harvestRef.Date_Harvested__c;
    		h.QuantityAccepted = harvestRef.Quantity_Accepted__c;
    		h.QuantityHarvested = harvestRef.Quantity_Harvested__c;
    		h.QuantityRejected = harvestRef.Quantity_Rejected__c;
    		h.StorageLocation = harvestRef.Storage_Location__c;
    		h.Id = harvestRef.Id;
    		
    		// add the harvest to the loan
    		l.Harvest = h;
    	}
    	
		return l;

		
	}
	
	public class Harvest {
		public String Id { get; set; }
		public String Crop { get; set; }
		public Date DateHarvested { get; set; }
		public Decimal QuantityAccepted { get; set; }
		public Decimal QuantityHarvested { get; set; }
		public Decimal QuantityRejected { get; set; }
		public String StorageLocation{ get; set; }
		
	}
	
}