ewarehouse-apex/api/src/objects/Loan__c.object
<CustomObject>
    <description>The loan that has been taken out by the farmer</description>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Loan_Repayment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Loan Repayments</relationshipLabel>
        <relationshipName>Loan_Repayments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Loan Repayments</relationshipLabel>
        <relationshipName>Loan_Repayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Repayment</label>
    <nameField>
        <displayFormat>LRN-{00000}</displayFormat>
        <label>Loan Repayment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Repayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/objects/Sale__c.object
<CustomObject>
    <description>Represents a sale transaction from the warehouse</description>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/LoanRepaymentRestService.cls
@RestResource(urlMapping='/ewarehouse/repayments/*')
global class LoanRepaymentRestService extends EwarehouseServiceBase  {
	
	@HttpGet
    global static ServiceResultResponse getRepayments() {
    	
    	Map<String, String> params = null;
		
		// get the id from the request parameter
		String loanId = RestContext.request.params.get('LoanId');
		
		if(loanId == null){
			System.debug('ERROR: request param [LoanId] should not be null');
			return new ErrorResponse('We could find required parameter [LoanId]');
		}
        
        system.debug('LoanId = ' + loanId);
        
        // get all the sObjects
        List<Repayment> repayments = new List<Repayment>();
        List<Loan_Repayment__c> sfRepayments;
        try {
        	sfRepayments = EwarehouseServiceBase.dataSource.getLoanRepayments(loanId);
        }
        catch(Exception e){
        	system.debug('ERROR: ' + e);
	       	return new ExceptionResponse(e);
        }
        		
        // iterate through repayments and convert to objects for json														
		for(Loan_Repayment__c lr: sfRepayments){
			
			Repayment item = new Repayment();
			item.Amount = lr.Amount__c;
			item.PaymentDate = lr.Payment_Date__c;
			item.Remarks = lr.Remarks__c;
			item.LoanId = lr.Loan__c;
			item.SaleId = lr.Sale__c;
			
			repayments.add(item);
		}

		// return the Loan Repayments
		return new RepaymentResponse(repayments);
	}
	
	@HttpPost
	global static ServiceResultResponse addRepayments(){ 
		
		// list of repayments to be stored
		List<Loan_Repayment__c> loanRepayments = new List<Loan_Repayment__c>();
		
		// take the client from the parameters
		String jsonString = RestContext.request.requestBody.toString();	
		system.debug('json: ' + jsonString);
		
		// parse the client data
		List<Repayment> repayments = null;
		try{
			repayments = (List<Repayment>) JSON.deserialize(jsonString, List<Repayment>.class);
			
			// Loop through the repayments and convert to SObjects
			for(Repayment item : repayments){
				Loan_Repayment__c lr = new Loan_Repayment__c();
				lr.Amount__c = item.Amount;
				lr.Payment_Date__c = item.PaymentDate;
				lr.Remarks__c = item.Remarks;
				lr.Loan__c = item.LoanId;
				lr.Sale__c = item.SaleId;
				loanRepayments.add(lr);
			}
		}
		catch(Exception e){
			system.debug('EXCEPTION: ' + e);
	       	return new ExceptionResponse(e);
		}
		
		if(loanRepayments.size() > 9000){
			return new ErrorResponse('Only 9000 records are allowed in one batch, please split the upload in smaller amounts');
		}
		
		system.debug('Repayments: ' + repayments);
	
		// insert the loan repayments
		Database.Saveresult[] results = null;
		try {
			system.debug('tester-start');
			results = EwarehouseServiceBase.dataSource.addLoanRepayments(loanRepayments);
			system.debug(results);
			system.debug('tester-end');
			
		}
		catch(Exception e){
			system.debug('EXCEPTION: ' + e);
	       	return new ExceptionResponse(e);
		}
		
		// check if there where errors
		boolean errors = false;
		String errorMessage = '';
		for(Database.SaveResult result : results){
			if(!result.isSuccess()){
				errors = true;
				errorMessage += '--------------------------\n';
				for(Database.Error err : result.getErrors()){
					errorMessage += err.getStatusCode() + ':' + err.getMessage() + '\n\n';
				}
			}
		}
		// check whether there were errors during posting
		if(errors){
			system.debug(errorMessage);
			return new ErrorResponse('Error while posting loan repayments:\n ' + errorMessage);
		}
		
		// return success if no errors occured
		return new SuccessResponse('Loan repayments posted successfully.');
	}
	
	global class RepaymentResponse extends ServiceResultResponse {
		public RepaymentResponse(Repayment[] repayments){
			this.code = '200';
			this.description = 'OK';
			this.repayments = repayments;
		}
		
		public Repayment[] repayments;
	}
	
	public class Repayment {
		public String Id { get; set; }
		public String LoanId { get; set; }
		public String SaleId { get; set; }
		public Decimal Amount { get; set; }
		public String Remarks { get; set; }
		public Date PaymentDate { get; set; }
	}

}