ewarehouse-apex/api/src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ewarehouse-apex/api/src/classes/EWarehouseMEDashboardControllerTest.cls
@isTest
public with sharing class EWarehouseMEDashboardControllerTest {
	
	static void loadTestData(){
		 // insert test data
        DataSourceMock.insertTestData();
        
        Country__c country = DataSourceMock.getTestCountry();
        insert country;
        
        District__c district = DataSourceMock.getTestDistrict();
        insert district;
        
		Person__c vkw = DataSourceMock.getTestPerson(country, district);
        vkw.Type__c = 'VKW';
        insert vkw;
        
	}
     
    static testMethod void testConstructor(){
        loadTestData();
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        
        
    }
    
    static testMethod void getImpactData(){
        
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> impactData = controller.getImpactData();
        
        System.assertEquals(impactData.size(), 8);
        System.assertEquals('No of Farmers registered', impactData[0].Name);
        System.assertEquals('2', impactData[0].Count);
        System.assertEquals('Female', impactData[1].Name);
        System.assertEquals('1', impactData[1].Count);
        System.assertEquals('Male', impactData[2].Name);
        System.assertEquals('1', impactData[2].Count);
        System.assertEquals('No of Village Knowledge Workers registered', impactData[3].Name);
        System.assertEquals('1', impactData[3].Count);
        System.assertEquals('Total loans', impactData[4].Name);
        System.assertEquals('2', impactData[4].Count);
        System.assertEquals('Repaid loans', impactData[5].Name);
        System.assertEquals('1', impactData[5].Count);
        System.assertEquals('Repaid ratio (loans)', impactData[6].Name);
        System.assertEquals('0.50', impactData[6].Count);
        System.assertEquals('No of farmers fully paid for sales', impactData[7].Name);
        System.assertEquals('2', impactData[7].Count);
        
    }
    
    static testMethod void getFarmersByGender(){
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> testData = controller.getFarmersByGender();
        
        System.assertEquals(testData.size(), 2);
        System.assertEquals('Female', testData[0].Name);
        System.assertEquals('1', testData[0].Count);
        System.assertEquals('Male', testData[1].Name);
        System.assertEquals('1', testData[1].Count);
    }
    
    static testMethod void getFarmersByAcre(){
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> testData = controller.getFarmersByAcre();
        
        System.assertEquals(testData.size(), 5);
        System.assertEquals('0 - 10', testData[0].Name);
        System.assertEquals('1', testData[0].Count);
        System.assertEquals('11 - 20', testData[1].Name);
        System.assertEquals('0', testData[1].Count);
        System.assertEquals('21 - 30', testData[2].Name);
        System.assertEquals('0', testData[2].Count);
        System.assertEquals('31 - 40', testData[3].Name);
        System.assertEquals('1', testData[3].Count);
        System.assertEquals('> 40', testData[4].Name);
        System.assertEquals('0', testData[4].Count);
       
    }
    
    static testMethod void getFarmersByCrop(){
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> testData = controller.getFarmersByCrop();
        
        System.assertEquals(1, testData.size());
        System.assertEquals('Maize', testData[0].Name);
        System.assertEquals('2', testData[0].Count);
    }
    
    static testMethod void getFarmersByLivestock(){
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> testData = controller.getFarmersByLivestock();
        
        System.assertEquals(1, testData.size());
        System.assertEquals('Goats', testData[0].Name);
        System.assertEquals('2', testData[0].Count);
    }
    
    static testMethod void getGrainCollected(){
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> testData = controller.getGrainCollected();
        System.debug('getGrainCollected' + testData);
        System.assertEquals(1, testData.size());
        System.assertEquals('Beans', testData[0].Name);
        System.assertEquals('180', testData[0].Count);
    }
    
    static testMethod void getGrainSold(){
        loadTestData();
        
        EWarehouseMEDashboardController controller = new EWarehouseMEDashboardController();
        List<EWarehouseMEDashboardController.NameCount> testData = controller.getGrainSold();
        System.debug('getGrainSold' + testData);
        System.assertEquals(0, testData.size());
        //System.assertEquals('Goats', testData[0].Name);
        //System.assertEquals('2', testData[0].Count);
    }
    
    
    
   // public class NameCount 
    
    //public class IntegerRange 
}